# BD CONFIG
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/swsbd?useSSL=false
      username: root
      password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
  messages:
    basename: i18n/messages